### ISSUE TITLE
simplest-proxy deploy failure

### ISSUE THREAD

**Issue by baluspalanisamy** [apigee/api-platform-samples#109]
../../setup/userconf.sh: line 13: $'\r': command not found
../../setup/userconf.sh: line 19: syntax error near unexpected token `$'\r''
'./../setup/userconf.sh: line 19: `_get_var()

**Comment by baluspalanisamy** [comment]
../../setup/userconf.sh: line 13: $'\r': command not found
../../setup/userconf.sh: line 19: syntax error near unexpected token `$'\r''
'./../setup/userconf.sh: line 19: `_get_var()

**Comment by WWitman** [comment]
I'm running a bash shell on MacOs, and it works as expected. If you're on a PC, maybe that is causing a problem. I found this information -- does it help? https://stackoverflow.com/questions/11616835/r-command-not-found-bashrc-bash-profile/32912867
