### ISSUE TITLE
is it ok to use pull request to add repos?

### ISSUE THREAD

**Issue by lamoboos223** [apigee/api-platform-samples#125]
I'm planning to open source some of my code on Apigee like a shared flow that takes the request payload and assign it as query string. and another project to camel case the payload or snake case it.

is it ok to add those sample in Apigee's space? as I don't have the target audience I want to share this code with.

thank you.
Lama.

**Comment by DinoChiesa** [comment]
The examples here are curated and managed by Apigee, particularly the documentation team. If you want to publish samples, please do!   You cando that in your own repos. 

If you have contributions you'd like to make, you can file a pull request, and we'll have a look at it. 

I know this is a really old message. Sorry about the long delay in responding. I thought I'd respond anyway, in case future readers had the same question.
