### ISSUE TITLE
Missing json_threat_protection.xsd

### ISSUE THREAD

**Issue by ghost** [apigee/api-platform-samples#19]
There's a reference to json_threat_protection.xsd in policies/all.xsd.  The referenced .xsd is missing from the "policies" directory.

**Comment by WWitman** [comment]
NB: All of the available policy schemas are available here: https://github.com/apigee/api-platform-samples/tree/master/schemas/policy

**Comment by WWitman** [comment]
The policy schema is available in the above mentioned repo.
