### ISSUE TITLE
incorrect link in documentation

### ISSUE THREAD

**Issue by kbrinner** [apigee/api-platform-samples#96]
In the intro:

> Audience
> You are an Apigee Edge API proxy developer, or you would like to learn about developing APIs that run on Apigee Edge. At a minimum, we assume you're familiar with Apigee Edge and how to create simple API proxies. To learn more, we recommend this **getting-started tutorial**.

The link to the getting-started tutorial gives a 404. I'm guessing it should go here instead:
https://docs.apigee.com/api-platform/get-started/get-started

**Comment by WWitman** [comment]
Thank you for reporting the broken link! It's fixed now.
