### ISSUE TITLE
How do I get the 'oauth-advanced' sample to work with SSO?

### ISSUE THREAD

**Issue by datta016** [apigee/api-platform-samples#98]
Our enterprise has SSO set up for logging into Apigee. As a result, I can no longer deploy this sample successfully. This makes sense as the sample is following Basic Authentication. Could anyone give guidance on how to switch from Basic Authentication and use SSO Bearer Tokens instead? I tried altering a few files, but unfortunately continue to receive the following error:

Error: Get API info returned status 401

Any help would be greatly appreciated!

**Comment by akoo1010** [comment]
Hi Datta016,
That is a non-trivial change in architecture and wouldn't be covered in this sample. We recommend posting specific questions on this in community.apigee.com for such a request.
